minecraft: "1.21"
id: 2re
name: 2mal3s Recipes
description: "Adds, changes fixes and upgrades 450+ recipes to improve the overall game experience while still keeping the vanilla feel."
author: 2mal3
version: "v1.11.0"

output: "build"

data_pack:
  name: 2mal3s-Recipes
  description: "v1.11.0"
  load:
    - "src"
    - pack.png: "pack.png"

pipeline:
  - mecha
  - plugins.installation_advancement
  - plugins.generate_recipe_advancements
require:
  - bolt

meta:
  bolt:
    entrypoint:
      - 2re:minecraft
      - 2re:2re/wood_cut
      - 2re:2re/undo_stairs_slabs
      - 2re:2re/stone_tools
      - 2re:2re/iron_alternative

  installation_advancement:
    icon:
      id: minecraft:crafting_table
