id: 2re
name: 2mal3s Recipes
description: "Adds, changes fixes and upgrades 450+ recipes to improve the overall game experience while still keeping the vanilla feel."
author: 2mal3
version: "v1.10.1"
minecraft: "1.20"

output: build

data_pack:
  name: 2mal3s-Recipes
  description: "v1.10.1"
  load:
    - src
    - pack.png: "pack.png"

pipeline:
  - mecha
  - plugins.generate_recipe_advancements
  - plugins.installation_advancement
require:
  - bolt

meta:
  vanilla:
    version: "1.20"

  bolt:
    entrypoint:
      - 2re:minecraft
      - 2re:2re/wood_cut
      - 2re:2re/undo_stairs_slabs
      - 2re:2re/stone_tools

  installation_advancement:
    icon:
      item: minecraft:crafting_table
