[tool.poetry]
name = "2mal3s-recipes"
version = "1.9.1"
description = ""
authors = ["2mal3 <56305732+2mal3@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
beet = "~0.103"
mecha = "~0.80"
bolt = "~0.38"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
