name: Lint

on:
  push:
    paths:
      - "**.bolt"
      - "**.json"
      - "**.mcfunction"
      - "beet.yaml"
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

env:
  VERSION: '1.20'
  NAME: '2mal3s-Recipes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup cache
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.lock') }}
      - name: Install dependencies
        run: |
          sed '/-e/d' requirements.lock > requirements.txt
          pip install -r requirements.txt

      - name: Build
        run: beet

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            build/${{ env.NAME }}

  mc-commands:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Check minecraft commands
        uses: mcbeet/check-commands@v1
        with:
          version: "0.86.2"
          source: "."
          minecraft: ${{ env.VERSION }}
          stats: true

  json:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Install jsonlint
        run: npm install -g jsonlint
      - name: Lint json files
        run: for file in $(find . -name '*.json'); do jsonlint $file -c -q; done
