name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  NAME: ''
  MODRINTH_ID: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup cache
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.lock') }}
      - name: Install dependencies
        run: |
          sed '/-e/d' requirements.lock > requirements.txt
          pip install -r requirements.txt

      - name: Build
        run: beet

      - name: Squash datapack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: v0.4.0
          artifact_name: datapack-raw
          options: |
            pack_directory = "build/${{ env.NAME }}"
            output_file_path = "${{ env.NAME }}.zip"
      - name: Add secondary files to datapack
        run: zip -u ${{ env.NAME }} LICENSE.txt README.md CHANGELOG.md

      - name: Squash resourcepack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: v0.4.0
          artifact_name: resourcepack-raw
          options: |
            pack_directory = "build/${{ env.NAME }}-Resourcepack"
            output_file_path = "${{ env.NAME }}-Resourcepack.zip"
      - name: Add secondary files to resourcepack
        run: zip -u ${{ env.NAME }}-Resourcepack LICENSE.txt README.md CHANGELOG.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            CHANGELOG.md
            ${{ env.NAME }}.zip
            ${{ env.NAME }}-Resourcepack.zip

  release-github:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.NAME }} ${{github.ref_name}}
          body_path: CHANGELOG.md
          files: |
            ${{ env.NAME }}.zip
            ${{ env.NAME }}-Resourcepack.zip

  release-modrinth:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish on Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            ${{ env.NAME }}.zip
            ${{ env.NAME }}-Resourcepack.zip
          name: ${{ env.NAME }} ${{github.ref_name}}
          version: ${{github.ref_name}}
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: datapack
          game-versions: |
            1.20.4
