name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  NAME: ''
  MODRINTH_ID: ''

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.lock

      - name: Build
        run: beet

      - name: Squash datapack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: v0.4.0
          artifact_name: datapack-raw
          options: |
            pack_directory = "build/${{ env.NAME }}"
            output_file_path = "${{ env.NAME }}.zip"
      - name: Add secondary files to datapack
        run: zip -u ${{ env.NAME }} LICENSE.txt README.md CHANGELOG.md

      - name: Squash resourcepack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: v0.4.0
          artifact_name: resourcepack-raw
          options: |
            pack_directory = "build/${{ env.NAME }}-Resourcepack"
            output_file_path = "${{ env.NAME }}-Resourcepack.zip"
      - name: Add secondary files to resourcepack
        run: zip -u ${{ env.NAME }}-Resourcepack LICENSE.txt README.md CHANGELOG.md

      - name: Publish on Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-unfeature-mode: intersection

          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: ${{ env.NAME }} ${{github.ref_name}}
          version: ${{github.ref_name}}
          version-type: release
          changelog-file: CHANGELOG.md
          files: |
            ${{ env.NAME }}.zip
            ${{ env.NAME }}-Resourcepack.zip

          loaders: datapack
          game-versions: |
            1.20.6
