name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1.2.1
        with:
          virtualenvs-in-project: true
      - name: Setup cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install

      - name: Build datapack
        run: poetry run beet

      - name: Squash datapack
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: build/2mal3s-Recipes
          artifact_name: datapack-raw
          force_include_files: icon.png
      - name: Download datapack-raw
        uses: actions/download-artifact@v3
        with:
          name: datapack-raw
      - name: Finish datapack
        run: |
          mv pack.zip 2mal3s-Recipes.zip
          zip -u 2mal3s-Recipes.zip LICENSE.txt README.md CHANGELOG.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            CHANGELOG.md
            2mal3s-Recipes.zip

  release-github:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: 2mal3s-Recipes ${{github.ref_name}}
          body_path: CHANGELOG.md
          files: |
            2mal3s-Recipes.zip

  release-modrinth:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Publish on Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: hIlFLwrl
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: 2mal3s-Recipes.zip
          name: 2mal3s Recipes ${{github.ref_name}}
          version: ${{github.ref_name}}
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: datapack
          game-versions: |
            1.19
            1.19.1
            1.19.2
            1.19.3
