name: Test

on:
  push:
    paths:
        - "**.json"

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jsonlint
        run: npm install -g jsonlint
      - name: Lint json files
        run: for file in $(find . -name "*.json"); do jsonlint $file -c -q; done
